env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/vue3-recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  # If there are rules that conflict with prettier, check with eslint-config-prettier, and disable them here
  # pnpx eslint-config-prettier vite.config.ts
  # https://prettier.io/docs/en/option-philosophy.html
  # https://github.com/prettier/eslint-config-prettier
  indent:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
  semi:
    - error
    - never
  spaced-comment:
    - error
    - always
  brace-style:
    - error
    - 1tbs
  '@typescript-eslint/no-unused-vars':
    - error
    - ignoreRestSiblings: true
  '@typescript-eslint/ban-ts-comment':
    - off
  'vue/max-attributes-per-line':
    - off
  'vue/valid-v-slot':
    - error
    - allowModifiers: true
  'vue/singleline-html-element-content-newline':
    - error
    - ignores:
#       https://github.com/vuejs/eslint-plugin-vue/issues/827
        - pre
        - textarea
        - 'router-link'
        - button
        - a
        - abbr
        - audio
        - b
        - bdi
        - bdo
        - canvas
        - cite
        - code
        - data
        - del
        - dfn
        - em
        - i
        - iframe
        - ins
        - kbd
        - label
        - map
        - mark
        - noscript
        - object
        - output
        - picture
        - q
        - ruby
        - s
        - samp
        - small
        - span
        - strong
        - sub
        - sup
        - svg
        - time
        - u
        - var
        - video
